### ISSUE TITLE
Cursor is still not visible

### ISSUE THREAD

**Issue by jkelol111** [likidu/kaido#7]
**Bug: Cursor is still not visible**

**Expected behavior:**

Cursor appears for login page navigation

**Actual behavior:**

Cursor does not appear after clicking "Sign In" button, therefore I couldn't navigate through the page to sign in (well, I could only get to the part where the OAuth screen asks me to accept the scopes that this app uses to access my MS account, and I couldn't click the "Yes" button because of no cursor, it keeps focusing on something if I click the Center key and brings up an empty dialog, which will disappear if the Center key is clicked again).

**Commands ran to build app & build environment:**

OS: Ubuntu 18.04 on Windows Subsystem for Linux (WSL 1)

Node: 12.16.1

yarn: 1.22.4

Commands ran:

- `yarn install` (successful)

- `yarn build` (successful)

- `cp -r ~/Downloads/kaido/build/* /mnt/d/Downloads/kaido` (successful)

- Use WebIDE in Pale Moon to deploy the app onto the device.

**Device information:**

Device: Nokia 8110 4G

KaiOS version: 2.5.1

Firmware version: 17.00.17.01

**Comment by jkelol111** [comment]
I have submitted a PR to fix this issue.

**Comment by likidu** [comment]
Solved in #8
